### ISSUE TITLE
Analise: Analytics and Metrics Orchestration

### ISSUE THREAD

**Issue by jorgesanchezperez** [OpenBankingToolkit/openbanking-reference-implementation#342]
As a developer I want to have document so that I can understand properly how analytics and metrics works.

## Acceptance criteria

- Understand how analytics and metrics are orchestrated
- Have documentation

## Tasks
List of tasks required to implement this story

- [ ] Analyse analytics and metrics implementation
- [ ] Identify improvement points
- [ ] Analyse analytics UI application
- [ ] Create documentation

### Release Notes

Affected App: Analytics and Metrics

Description: X
<end release notes>

**Comment by BohoCode** [comment]
This looks a bit open ended to me. Can we just focus on fixing the current bug? We need to get a fix within a day really and get on with our upcoming project/tasks

**Comment by BohoCode** [comment]
Because we will probably change analytics soon. The current design is very coupled and brittle. I would rather use some standard industry patterns e.g. log file based analytics using splunk or something similar.

**Comment by jorgesanchezperez** [comment]
- Create user by directory UI (forgerock-openbanking-ui): the app call directly AM to register the user (TPP, PSU)
   `POST /json/realms/root/realms/auth/selfservice/userRegistration?_action=submitRequirements`

**Comment by jorgesanchezperez** [comment]
Close to focus to fix a specific issue created #343
